framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    cache:
        default_redis_provider:
            'redis://%env(REDIS_HOST)%'
        pools:
            custom.cache:
                adapter: cache.adapter.redis

    #esi: true
    #fragments: true
    php_errors:
        log: true
