security:
    encoders:
        App\Entity\User:
            algorithm: text
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            switch_user: true
            logout:
                path:   /logout
                target: /
                invalidate_session: true
            guard:
                authenticators:
                    - App\Security\AppSecurityAuthenticator
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_SELLER, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
