version: '3.2'

services:
  app:
    image: nginx:alpine
    working_dir: /srv
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/srv/
  php:
    build:
      context: ./docker/php
    working_dir: /srv
    volumes:
      - .:/srv/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini
      - ./docker/php/entrypoint.sh:/usr/bin/entrypoint
  node:
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - .:/srv/
      - ./docker/node/entrypoint.sh:/usr/local/bin/entrypoint
  redis:
    image: redis:5.0.5
